### ISSUE TITLE
Support fro Spark 2.0?

### ISSUE THREAD

**Issue by jlcalbre** [hazelcast/hazelcast-spark#4]
Is there any work being done to provide support fro Spark 2.0?

**Comment by brijeshkec11** [comment]
any update for spark 2.0.1 support?

**Comment by davidrabinowitz** [comment]
+1

We have Spark 2.1.0 now...

**Comment by alladivasu** [comment]
Thank you @davidrabinowitz 

Is it in GA now?

**Comment by davidrabinowitz** [comment]
@alladivasu Yes, Released on Dec 28, 2016. AWS also supports it with the [emr-5.3.0 release](http://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-whatsnew.html)

**Comment by enesakar** [comment]
guys sorry for late answer. I will talk with team and clarify the target for spark 2

**Comment by davidrabinowitz** [comment]
Thanks @enesakar

**Comment by jlcalbre** [comment]
FYI, we've cloned the repo and done some experimenting.  It seems all you need to do is change the dependency to the newer version of Spark (for 2.02, at least), recompile the jar and it works fine.  There me be some deeper functionality we have missed, and have only tested the write to map function, but there were no issues there.

**Comment by davidrabinowitz** [comment]
@jlcalbre have you switched to Scala 2.11 as well? Were there any issues?

**Comment by jlcalbre** [comment]
@davidrabinowitz  I built the hazelcast-spark jar off of spark-core_2.11 which uses scala 2.11.  My application that uses the hazelcast-spark connector is also built off of 2.11.  I haven;t seen any issues yet, but like I said, I've used it in pretty limited circumstances so far so can't guarantee anything.

Also, for completeness, I did the build via a pom.xml file since sbt doesn't play nice in our world.

**Comment by enesakar** [comment]
Talked to the team, we will work on this next week.

**Comment by davidrabinowitz** [comment]
Thanks :-)

**Comment by emrahkocaman** [comment]
#5, PR has been sent to upgrade Spark v2.1.0.

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-spark/pull/5
